version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: customer-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: customer_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  customer-service:
    build: .
    container_name: customer-service
    restart: always
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/customer_service
      DB_USER: postgres
      DB_PASSWORD: 12345
      KAFKA_SERVER: kafka:9092
      MAIL_USER: temperory789@gmail.com
      MAIL_PASS: ufwwsufczxhmkqsi
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - kafka

volumes:
  postgres_data:
